app:
  name: XishangOS-backend
  #addresses: 192.168.100.161
  port: 8080
  mode: debug  # debug or release
  use-multipoint: false

database:
  type: mysql
  enable-foreign-key: true # 是否启用数据库外键
  mysql:
    address: 82.156.146.136
    port: 13307
    conn-config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: xishang_os
    username: xishang
    password: Xishang@dev66
    max-idle-conn: 10
    max-open-conn: 100

zap:
  level: debug
  prefix: ''
  format: console
  path: /tmp # 日志目录
  file-shunt: false # 日志文件是否按级别分流
  max-age: 10 # 日志文件保留最大天数
  max-backups: 10 # 日志文件最大个数
  max-size: 1 # 日志文件最大大小
  log-in-console: true
  encode-level: LowercaseLevelEncoder
  stacktrace-key: stacktrace

captcha:
  enabled: true
  key-long: 4
  img-width: 240
  img-height: 80
  expiration: 180 # 过期时间，单位秒
  pre-key: "XishangOS:PUBLIC:CAPTCHA:" # 存储到redis的前缀
  source: "abcdefghjkmnpqrstuvwxyz23456789" # 可用字符集
  noise-count: 50 # 背景噪点数
  show-line-options: 20 # 干扰线数量

redis:
  address: 82.156.146.136
  port: 16377
  password: Xishang@dev66
  db: 0

jwt:
  signing-key: c39ed162-65f7-4b49-983f-cdda998e9f2c
  expires-time: 7d
  buffer-time: 1d
  issuer: xishang