// +build tools
// +build tools
// Code generated by ent, DO NOT EDIT.

package codegen

import (
	"time"

	"github.com/wangxg422/XishangOS-backend/app/module/application/model/schema"
	"github.com/wangxg422/XishangOS-backend/app/module/application/model/schema/codegen/appinstance"
	"github.com/wangxg422/XishangOS-backend/app/module/application/model/schema/codegen/apppackage"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appinstanceMixin := schema.AppInstance{}.Mixin()
	appinstanceMixinFields0 := appinstanceMixin[0].Fields()
	_ = appinstanceMixinFields0
	appinstanceMixinFields1 := appinstanceMixin[1].Fields()
	_ = appinstanceMixinFields1
	appinstanceMixinFields2 := appinstanceMixin[2].Fields()
	_ = appinstanceMixinFields2
	appinstanceFields := schema.AppInstance{}.Fields()
	_ = appinstanceFields
	// appinstanceDescCreatedAt is the schema descriptor for created_at field.
	appinstanceDescCreatedAt := appinstanceMixinFields1[0].Descriptor()
	// appinstance.DefaultCreatedAt holds the default value on creation for the created_at field.
	appinstance.DefaultCreatedAt = appinstanceDescCreatedAt.Default.(func() time.Time)
	// appinstanceDescUpdatedAt is the schema descriptor for updated_at field.
	appinstanceDescUpdatedAt := appinstanceMixinFields1[1].Descriptor()
	// appinstance.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	appinstance.DefaultUpdatedAt = appinstanceDescUpdatedAt.Default.(func() time.Time)
	// appinstance.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	appinstance.UpdateDefaultUpdatedAt = appinstanceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// appinstanceDescDeleteAt is the schema descriptor for delete_at field.
	appinstanceDescDeleteAt := appinstanceMixinFields1[2].Descriptor()
	// appinstance.DefaultDeleteAt holds the default value on creation for the delete_at field.
	appinstance.DefaultDeleteAt = appinstanceDescDeleteAt.Default.(func() time.Time)
	// appinstance.UpdateDefaultDeleteAt holds the default value on update for the delete_at field.
	appinstance.UpdateDefaultDeleteAt = appinstanceDescDeleteAt.UpdateDefault.(func() time.Time)
	// appinstanceDescStatus is the schema descriptor for status field.
	appinstanceDescStatus := appinstanceMixinFields2[0].Descriptor()
	// appinstance.DefaultStatus holds the default value on creation for the status field.
	appinstance.DefaultStatus = appinstanceDescStatus.Default.(int8)
	// appinstanceDescID is the schema descriptor for id field.
	appinstanceDescID := appinstanceMixinFields0[0].Descriptor()
	// appinstance.DefaultID holds the default value on creation for the id field.
	appinstance.DefaultID = appinstanceDescID.Default.(func() int64)
	apppackageMixin := schema.AppPackage{}.Mixin()
	apppackageMixinFields0 := apppackageMixin[0].Fields()
	_ = apppackageMixinFields0
	apppackageMixinFields1 := apppackageMixin[1].Fields()
	_ = apppackageMixinFields1
	apppackageMixinFields2 := apppackageMixin[2].Fields()
	_ = apppackageMixinFields2
	apppackageFields := schema.AppPackage{}.Fields()
	_ = apppackageFields
	// apppackageDescCreatedAt is the schema descriptor for created_at field.
	apppackageDescCreatedAt := apppackageMixinFields1[0].Descriptor()
	// apppackage.DefaultCreatedAt holds the default value on creation for the created_at field.
	apppackage.DefaultCreatedAt = apppackageDescCreatedAt.Default.(func() time.Time)
	// apppackageDescUpdatedAt is the schema descriptor for updated_at field.
	apppackageDescUpdatedAt := apppackageMixinFields1[1].Descriptor()
	// apppackage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	apppackage.DefaultUpdatedAt = apppackageDescUpdatedAt.Default.(func() time.Time)
	// apppackage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	apppackage.UpdateDefaultUpdatedAt = apppackageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// apppackageDescDeleteAt is the schema descriptor for delete_at field.
	apppackageDescDeleteAt := apppackageMixinFields1[2].Descriptor()
	// apppackage.DefaultDeleteAt holds the default value on creation for the delete_at field.
	apppackage.DefaultDeleteAt = apppackageDescDeleteAt.Default.(func() time.Time)
	// apppackage.UpdateDefaultDeleteAt holds the default value on update for the delete_at field.
	apppackage.UpdateDefaultDeleteAt = apppackageDescDeleteAt.UpdateDefault.(func() time.Time)
	// apppackageDescStatus is the schema descriptor for status field.
	apppackageDescStatus := apppackageMixinFields2[0].Descriptor()
	// apppackage.DefaultStatus holds the default value on creation for the status field.
	apppackage.DefaultStatus = apppackageDescStatus.Default.(int8)
	// apppackageDescID is the schema descriptor for id field.
	apppackageDescID := apppackageMixinFields0[0].Descriptor()
	// apppackage.DefaultID holds the default value on creation for the id field.
	apppackage.DefaultID = apppackageDescID.Default.(func() int64)
}
