// Code generated by ent, DO NOT EDIT.

package codegen

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wangxg422/XishangOS-backend/app/module/system/model/schema/codegen/predicate"
	"github.com/wangxg422/XishangOS-backend/app/module/system/model/schema/codegen/syscasbinrule"
)

// SysCasbinRuleQuery is the builder for querying SysCasbinRule entities.
type SysCasbinRuleQuery struct {
	config
	ctx        *QueryContext
	order      []syscasbinrule.OrderOption
	inters     []Interceptor
	predicates []predicate.SysCasbinRule
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SysCasbinRuleQuery builder.
func (scrq *SysCasbinRuleQuery) Where(ps ...predicate.SysCasbinRule) *SysCasbinRuleQuery {
	scrq.predicates = append(scrq.predicates, ps...)
	return scrq
}

// Limit the number of records to be returned by this query.
func (scrq *SysCasbinRuleQuery) Limit(limit int) *SysCasbinRuleQuery {
	scrq.ctx.Limit = &limit
	return scrq
}

// Offset to start from.
func (scrq *SysCasbinRuleQuery) Offset(offset int) *SysCasbinRuleQuery {
	scrq.ctx.Offset = &offset
	return scrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (scrq *SysCasbinRuleQuery) Unique(unique bool) *SysCasbinRuleQuery {
	scrq.ctx.Unique = &unique
	return scrq
}

// Order specifies how the records should be ordered.
func (scrq *SysCasbinRuleQuery) Order(o ...syscasbinrule.OrderOption) *SysCasbinRuleQuery {
	scrq.order = append(scrq.order, o...)
	return scrq
}

// First returns the first SysCasbinRule entity from the query.
// Returns a *NotFoundError when no SysCasbinRule was found.
func (scrq *SysCasbinRuleQuery) First(ctx context.Context) (*SysCasbinRule, error) {
	nodes, err := scrq.Limit(1).All(setContextOp(ctx, scrq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{syscasbinrule.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (scrq *SysCasbinRuleQuery) FirstX(ctx context.Context) *SysCasbinRule {
	node, err := scrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SysCasbinRule ID from the query.
// Returns a *NotFoundError when no SysCasbinRule ID was found.
func (scrq *SysCasbinRuleQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = scrq.Limit(1).IDs(setContextOp(ctx, scrq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{syscasbinrule.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (scrq *SysCasbinRuleQuery) FirstIDX(ctx context.Context) int {
	id, err := scrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SysCasbinRule entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SysCasbinRule entity is found.
// Returns a *NotFoundError when no SysCasbinRule entities are found.
func (scrq *SysCasbinRuleQuery) Only(ctx context.Context) (*SysCasbinRule, error) {
	nodes, err := scrq.Limit(2).All(setContextOp(ctx, scrq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{syscasbinrule.Label}
	default:
		return nil, &NotSingularError{syscasbinrule.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (scrq *SysCasbinRuleQuery) OnlyX(ctx context.Context) *SysCasbinRule {
	node, err := scrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SysCasbinRule ID in the query.
// Returns a *NotSingularError when more than one SysCasbinRule ID is found.
// Returns a *NotFoundError when no entities are found.
func (scrq *SysCasbinRuleQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = scrq.Limit(2).IDs(setContextOp(ctx, scrq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{syscasbinrule.Label}
	default:
		err = &NotSingularError{syscasbinrule.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (scrq *SysCasbinRuleQuery) OnlyIDX(ctx context.Context) int {
	id, err := scrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SysCasbinRules.
func (scrq *SysCasbinRuleQuery) All(ctx context.Context) ([]*SysCasbinRule, error) {
	ctx = setContextOp(ctx, scrq.ctx, "All")
	if err := scrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SysCasbinRule, *SysCasbinRuleQuery]()
	return withInterceptors[[]*SysCasbinRule](ctx, scrq, qr, scrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (scrq *SysCasbinRuleQuery) AllX(ctx context.Context) []*SysCasbinRule {
	nodes, err := scrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SysCasbinRule IDs.
func (scrq *SysCasbinRuleQuery) IDs(ctx context.Context) (ids []int, err error) {
	if scrq.ctx.Unique == nil && scrq.path != nil {
		scrq.Unique(true)
	}
	ctx = setContextOp(ctx, scrq.ctx, "IDs")
	if err = scrq.Select(syscasbinrule.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (scrq *SysCasbinRuleQuery) IDsX(ctx context.Context) []int {
	ids, err := scrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (scrq *SysCasbinRuleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, scrq.ctx, "Count")
	if err := scrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, scrq, querierCount[*SysCasbinRuleQuery](), scrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (scrq *SysCasbinRuleQuery) CountX(ctx context.Context) int {
	count, err := scrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (scrq *SysCasbinRuleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, scrq.ctx, "Exist")
	switch _, err := scrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("codegen: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (scrq *SysCasbinRuleQuery) ExistX(ctx context.Context) bool {
	exist, err := scrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SysCasbinRuleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (scrq *SysCasbinRuleQuery) Clone() *SysCasbinRuleQuery {
	if scrq == nil {
		return nil
	}
	return &SysCasbinRuleQuery{
		config:     scrq.config,
		ctx:        scrq.ctx.Clone(),
		order:      append([]syscasbinrule.OrderOption{}, scrq.order...),
		inters:     append([]Interceptor{}, scrq.inters...),
		predicates: append([]predicate.SysCasbinRule{}, scrq.predicates...),
		// clone intermediate query.
		sql:  scrq.sql.Clone(),
		path: scrq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Ptype string `json:"ptype,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SysCasbinRule.Query().
//		GroupBy(syscasbinrule.FieldPtype).
//		Aggregate(codegen.Count()).
//		Scan(ctx, &v)
func (scrq *SysCasbinRuleQuery) GroupBy(field string, fields ...string) *SysCasbinRuleGroupBy {
	scrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SysCasbinRuleGroupBy{build: scrq}
	grbuild.flds = &scrq.ctx.Fields
	grbuild.label = syscasbinrule.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Ptype string `json:"ptype,omitempty"`
//	}
//
//	client.SysCasbinRule.Query().
//		Select(syscasbinrule.FieldPtype).
//		Scan(ctx, &v)
func (scrq *SysCasbinRuleQuery) Select(fields ...string) *SysCasbinRuleSelect {
	scrq.ctx.Fields = append(scrq.ctx.Fields, fields...)
	sbuild := &SysCasbinRuleSelect{SysCasbinRuleQuery: scrq}
	sbuild.label = syscasbinrule.Label
	sbuild.flds, sbuild.scan = &scrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SysCasbinRuleSelect configured with the given aggregations.
func (scrq *SysCasbinRuleQuery) Aggregate(fns ...AggregateFunc) *SysCasbinRuleSelect {
	return scrq.Select().Aggregate(fns...)
}

func (scrq *SysCasbinRuleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range scrq.inters {
		if inter == nil {
			return fmt.Errorf("codegen: uninitialized interceptor (forgotten import codegen/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, scrq); err != nil {
				return err
			}
		}
	}
	for _, f := range scrq.ctx.Fields {
		if !syscasbinrule.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("codegen: invalid field %q for query", f)}
		}
	}
	if scrq.path != nil {
		prev, err := scrq.path(ctx)
		if err != nil {
			return err
		}
		scrq.sql = prev
	}
	return nil
}

func (scrq *SysCasbinRuleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SysCasbinRule, error) {
	var (
		nodes = []*SysCasbinRule{}
		_spec = scrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SysCasbinRule).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SysCasbinRule{config: scrq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, scrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (scrq *SysCasbinRuleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := scrq.querySpec()
	_spec.Node.Columns = scrq.ctx.Fields
	if len(scrq.ctx.Fields) > 0 {
		_spec.Unique = scrq.ctx.Unique != nil && *scrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, scrq.driver, _spec)
}

func (scrq *SysCasbinRuleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(syscasbinrule.Table, syscasbinrule.Columns, sqlgraph.NewFieldSpec(syscasbinrule.FieldID, field.TypeInt))
	_spec.From = scrq.sql
	if unique := scrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if scrq.path != nil {
		_spec.Unique = true
	}
	if fields := scrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, syscasbinrule.FieldID)
		for i := range fields {
			if fields[i] != syscasbinrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := scrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := scrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := scrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := scrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (scrq *SysCasbinRuleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(scrq.driver.Dialect())
	t1 := builder.Table(syscasbinrule.Table)
	columns := scrq.ctx.Fields
	if len(columns) == 0 {
		columns = syscasbinrule.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if scrq.sql != nil {
		selector = scrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if scrq.ctx.Unique != nil && *scrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range scrq.predicates {
		p(selector)
	}
	for _, p := range scrq.order {
		p(selector)
	}
	if offset := scrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := scrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SysCasbinRuleGroupBy is the group-by builder for SysCasbinRule entities.
type SysCasbinRuleGroupBy struct {
	selector
	build *SysCasbinRuleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (scrgb *SysCasbinRuleGroupBy) Aggregate(fns ...AggregateFunc) *SysCasbinRuleGroupBy {
	scrgb.fns = append(scrgb.fns, fns...)
	return scrgb
}

// Scan applies the selector query and scans the result into the given value.
func (scrgb *SysCasbinRuleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scrgb.build.ctx, "GroupBy")
	if err := scrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SysCasbinRuleQuery, *SysCasbinRuleGroupBy](ctx, scrgb.build, scrgb, scrgb.build.inters, v)
}

func (scrgb *SysCasbinRuleGroupBy) sqlScan(ctx context.Context, root *SysCasbinRuleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(scrgb.fns))
	for _, fn := range scrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*scrgb.flds)+len(scrgb.fns))
		for _, f := range *scrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*scrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SysCasbinRuleSelect is the builder for selecting fields of SysCasbinRule entities.
type SysCasbinRuleSelect struct {
	*SysCasbinRuleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (scrs *SysCasbinRuleSelect) Aggregate(fns ...AggregateFunc) *SysCasbinRuleSelect {
	scrs.fns = append(scrs.fns, fns...)
	return scrs
}

// Scan applies the selector query and scans the result into the given value.
func (scrs *SysCasbinRuleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scrs.ctx, "Select")
	if err := scrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SysCasbinRuleQuery, *SysCasbinRuleSelect](ctx, scrs.SysCasbinRuleQuery, scrs, scrs.inters, v)
}

func (scrs *SysCasbinRuleSelect) sqlScan(ctx context.Context, root *SysCasbinRuleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(scrs.fns))
	for _, fn := range scrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*scrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
