// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/wangxg422/XishangOS-backend/app/module/application/model/schema"
	"github.com/wangxg422/XishangOS-backend/app/module/application/model/schema/codegen/appinstance"
	"github.com/wangxg422/XishangOS-backend/app/module/application/model/schema/codegen/apppackage"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appinstanceMixin := schema.AppInstance{}.Mixin()
	appinstanceMixinHooks6 := appinstanceMixin[6].Hooks()
	appinstance.Hooks[0] = appinstanceMixinHooks6[0]
	appinstanceMixinInters6 := appinstanceMixin[6].Interceptors()
	appinstance.Interceptors[0] = appinstanceMixinInters6[0]
	appinstanceMixinFields0 := appinstanceMixin[0].Fields()
	_ = appinstanceMixinFields0
	appinstanceMixinFields1 := appinstanceMixin[1].Fields()
	_ = appinstanceMixinFields1
	appinstanceMixinFields3 := appinstanceMixin[3].Fields()
	_ = appinstanceMixinFields3
	appinstanceMixinFields6 := appinstanceMixin[6].Fields()
	_ = appinstanceMixinFields6
	appinstanceFields := schema.AppInstance{}.Fields()
	_ = appinstanceFields
	// appinstanceDescCreatedAt is the schema descriptor for created_at field.
	appinstanceDescCreatedAt := appinstanceMixinFields1[0].Descriptor()
	// appinstance.DefaultCreatedAt holds the default value on creation for the created_at field.
	appinstance.DefaultCreatedAt = appinstanceDescCreatedAt.Default.(func() time.Time)
	// appinstanceDescUpdatedAt is the schema descriptor for updated_at field.
	appinstanceDescUpdatedAt := appinstanceMixinFields1[1].Descriptor()
	// appinstance.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	appinstance.DefaultUpdatedAt = appinstanceDescUpdatedAt.Default.(func() time.Time)
	// appinstance.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	appinstance.UpdateDefaultUpdatedAt = appinstanceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// appinstanceDescStatus is the schema descriptor for status field.
	appinstanceDescStatus := appinstanceMixinFields3[0].Descriptor()
	// appinstance.DefaultStatus holds the default value on creation for the status field.
	appinstance.DefaultStatus = appinstanceDescStatus.Default.(int8)
	// appinstanceDescDelFlag is the schema descriptor for del_flag field.
	appinstanceDescDelFlag := appinstanceMixinFields6[0].Descriptor()
	// appinstance.DefaultDelFlag holds the default value on creation for the del_flag field.
	appinstance.DefaultDelFlag = appinstanceDescDelFlag.Default.(int8)
	// appinstanceDescID is the schema descriptor for id field.
	appinstanceDescID := appinstanceMixinFields0[0].Descriptor()
	// appinstance.DefaultID holds the default value on creation for the id field.
	appinstance.DefaultID = appinstanceDescID.Default.(func() int64)
	apppackageMixin := schema.AppPackage{}.Mixin()
	apppackageMixinHooks6 := apppackageMixin[6].Hooks()
	apppackage.Hooks[0] = apppackageMixinHooks6[0]
	apppackageMixinInters6 := apppackageMixin[6].Interceptors()
	apppackage.Interceptors[0] = apppackageMixinInters6[0]
	apppackageMixinFields0 := apppackageMixin[0].Fields()
	_ = apppackageMixinFields0
	apppackageMixinFields1 := apppackageMixin[1].Fields()
	_ = apppackageMixinFields1
	apppackageMixinFields3 := apppackageMixin[3].Fields()
	_ = apppackageMixinFields3
	apppackageMixinFields6 := apppackageMixin[6].Fields()
	_ = apppackageMixinFields6
	apppackageFields := schema.AppPackage{}.Fields()
	_ = apppackageFields
	// apppackageDescCreatedAt is the schema descriptor for created_at field.
	apppackageDescCreatedAt := apppackageMixinFields1[0].Descriptor()
	// apppackage.DefaultCreatedAt holds the default value on creation for the created_at field.
	apppackage.DefaultCreatedAt = apppackageDescCreatedAt.Default.(func() time.Time)
	// apppackageDescUpdatedAt is the schema descriptor for updated_at field.
	apppackageDescUpdatedAt := apppackageMixinFields1[1].Descriptor()
	// apppackage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	apppackage.DefaultUpdatedAt = apppackageDescUpdatedAt.Default.(func() time.Time)
	// apppackage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	apppackage.UpdateDefaultUpdatedAt = apppackageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// apppackageDescStatus is the schema descriptor for status field.
	apppackageDescStatus := apppackageMixinFields3[0].Descriptor()
	// apppackage.DefaultStatus holds the default value on creation for the status field.
	apppackage.DefaultStatus = apppackageDescStatus.Default.(int8)
	// apppackageDescDelFlag is the schema descriptor for del_flag field.
	apppackageDescDelFlag := apppackageMixinFields6[0].Descriptor()
	// apppackage.DefaultDelFlag holds the default value on creation for the del_flag field.
	apppackage.DefaultDelFlag = apppackageDescDelFlag.Default.(int8)
	// apppackageDescID is the schema descriptor for id field.
	apppackageDescID := apppackageMixinFields0[0].Descriptor()
	// apppackage.DefaultID holds the default value on creation for the id field.
	apppackage.DefaultID = apppackageDescID.Default.(func() int64)
}

const (
	Version = "v0.13.0"                                         // Version of ent codegen.
	Sum     = "h1:DclxWczaCpyiKn6ZWVcJjq1zIKtJ11iNKy+08lNYsJE=" // Sum of ent codegen.
)
